swagger: '2.0'
info:
  description: An API that provides VTuber channel data for Thai VTuber Ranking site https://vtuber.chuysan.com/
  version: 1.0.0
  title: Thai VTuber Ranking API
  # put the contact info for your development or API team
  contact:
    name: Chuy
    url: https://twitter.com/chuymaster

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: public
  description: Operations available to regular developers. No authorization required.

paths:
  /list.json:
    get:
      tags:
      - public
      summary: Get channel data list
      description: Due to a limit from YouTube API, the data is divided into multiple arrays, which need to be combined on the client side.
      produces:
      - application/json
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Channel'
  /one_day_ranking.json:
    get:
      tags:
      - public
      summary: Get top video ranking in the past one day
      produces:
      - application/json
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Video'
  /three_days_ranking.json:
    get:
      tags:
      - public
      summary: Get top video ranking in the past three days
      produces:
      - application/json
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Video'
  /seven_days_ranking.json:
    get:
      tags:
      - public
      summary: Get top video ranking in the past seven days
      produces:
      - application/json
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Video'
  /chart_data/{id}.json:
    get:
      tags:
      - public
      summary: Get chart data
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        description: channel id
        required: true
        type: string
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/ChannelChartData'
        404:
          description: not found
  /live_videos.json:
    get:
      tags:
      - public
      summary: Get current live videos
      produces:
      - application/json
      responses:
        200:
          description: live_status will always be 1
          schema:
            type: array
            items:
              $ref: '#/definitions/LiveVideo'
  /upcoming_videos.json:
    get:
      tags:
      - public
      summary: Get upcoming live videos.
      produces:
      - application/json
      responses:
        200:
          description: live_status will always be 2
          schema:
            type: array
            items:
              $ref: '#/definitions/LiveVideo'
definitions:
  Channel:
    type: object
    required:
    - channel_id
    - updated_at
    - is_rebranded
    properties:
      channel_id:
        type: string
        example: UCqhhWjpw23dWhJ5rRwCCrMA
      title:
        type: string
        example: Aisha Channel
      description:
        type: string
        example: Guppa! Virtual Idol Aisha is here! \nMeet Aisha's enjoyable video contents here! ♡ (~￣▽￣)~
      thumbnail_icon_url:
        type: string
        format: url
        example: https://yt3.ggpht.com/ytc/AAUvwnikS_My8HysQaH0PMs1Ei7d3fBTSgFfKi_hZt7q3g=s240-c-k-c0x00ffffff-no-rj
      subscribers:
        type: integer
        example: 269000
      views:
        type: integer
        example: 18192572
      comments:
        type: integer
        example: 100
      videos:
        type: integer
        example: 225
      uploads:
        type: string
        example: UUqhhWjpw23dWhJ5rRwCCrMA
        description: an uploads playlist ID
      published_at:
        type: string
        format: date-time
        example: "2019-07-12T10:32:09Z"
      last_published_video_at:
        type: string
        format: date-time
        example: "2021-01-15T18:00:27Z"
      updated_at:
        type: integer
        format: timestamp
        example: 1611039613975
      is_rebranded:
        type: boolean
        example: false
        description: a flag indicating whether the channel is rebranded from other channel. `false` represents that this channel is an original VTuber channel.
    description: YouTube Channel Info
  ChartDataPoint:
    description: a specific point of chart
    type: object
    required:
    - date
    - views
    - subscribers
    - comments
    - videos
    properties:
      date:
        type: string
        format: date
        example: "2020-09-01"
      views:
        type: integer
        example: 1000
      subscribers:
        type: integer
        example: 100
      comments:
        type: integer
        example: 10
      videos:
        type: integer
        example: 10
  ChannelChartData:
    description: channel and data points
    type: object
    required:
    - id
    - title
    - chartDataPoints
    properties:
      id:
        type: string
        example: UCqhhWjpw23dWhJ5rRwCCrMA
      title:
        type: string
        example: Aisha Channel
      chartDataPoints:
        type: array
        items:
          $ref: '#/definitions/ChartDataPoint'
  Video:
    description: a video info
    type: object
    required:
    - id
    - title
    - channelId
    - channelTitle
    - thumbnailImageUrl
    - publishedAt
    - isRebranded
    - viewCount
    - commentCount
    - dislikeCount
    - favoriteCount
    - likeCount
    properties:
      id:
        type: string
        example: lDokdIbqu_I
      title:
        type: string
        example: LIVE ย้อนหลัง
      channelId:
        type: string
        example: UC7iCSRt7Jej2XE0MaM9gPgg
      channelTitle:
        type: string
        example: YuChan Channel
      thumbnailImageUrl:
        type: string
        format: url
        example: https://i.ytimg.com/vi/lDokdIbqu_I/hqdefault.jpg
      publishedAt:
        type: string
        format: date-time
        example: "2021-01-18T14:33:54Z"
      isRebranded:
        type: boolean
        example: false
      viewCount:
        type: integer
        example: 1000
      commentCount:
        type: integer
        example: 10
      dislikeCount:
        type: integer
        example: 10
      favoriteCount:
        type: integer
        example: 10
      likeCount:
        type: integer
        example: 100
  LiveVideo:
    description: a live video info
    type: object
    required:
    - id
    - title
    - channel_id
    - description
    - view_count
    - thumbnail_image_url
    - published_at
    - live_status
    properties:
      id:
        type: string
        example: lDokdIbqu_I
      title:
        type: string
        example: LIVE ย้อนหลัง
      channel_id:
        type: string
        example: UC7iCSRt7Jej2XE0MaM9gPgg
      description:
        type: string
        example: Video Description
      thumbnail_image_url:
        type: string
        format: url
        example: https://i.ytimg.com/vi/lDokdIbqu_I/hqdefault.jpg
      published_at:
        type: string
        format: date-time
        example: "2021-01-18T14:33:54Z"
      live_status:
        type: integer
        example: 1
        enum: [None, Live, Upcoming, Past]
      live_schedule:
        type: string
        format: date-time
        example: "2021-06-26T13:40:00Z"
        description: The scheduled start time of the live. Not available if live_status is None
      live_start:
        type: string
        format: date-time
        example: "2021-06-26T13:40:00Z"
        description: The actual start time of the live. Only available when live_status is Live or Past
      live_end:
        type: string
        format: date-time
        example: "2021-06-26T13:40:00Z"
        description: The actual end time of the live. Only available when live_status is Past
      live_concurrent_viewer_count:
        type: integer
        example: 100
        description: The number of concurrent viewer. Only available when live_status is Live
host: storage.googleapis.com
basePath: /thaivtuberranking.appspot.com/channel_data
schemes:
 - https
